# Neural Style Transfer
Gaty et. al, Image Style Transfer Using Convolutional Neural Networks, CVPR 2016

## Import Libraries
필요한 라이브러리들을 가져옵니다.

In [1]:
%pylab inline
import time
import os 

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim
import matplotlib.pyplot as plt
import torchvision
from torchvision import transforms

from PIL import Image

from collections import OrderedDict


Populating the interactive namespace from numpy and matplotlib


## Reshaping matrix
The shape of $a$ is $3\times2$ tensor.

$$a=
\begin{bmatrix}
1& 2\\
3& 4\\
5& 6
\end{bmatrix}$$

Let $b$ as a reshaped tensor which has shape of $2\times3$.

$$b=
\begin{bmatrix}
1& 2 & 3\\
4& 5 & 6
\end{bmatrix}$$



In [2]:
a = torch.Tensor([[1,2],[3,4], [5,6]])
print("Tensor a is: \n{}".format(a))
print("Tensor a is: {}".format(a.shape))

b = a.view(2, -1)
print("Tensor b is: \n{}".format(b))
print("Tensor b is: {}".format(b.shape))

Tensor a is: 
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Tensor a is: torch.Size([3, 2])
Tensor b is: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Tensor b is: torch.Size([2, 3])


In [3]:
x = torch.rand((1,3,224,224))
print("Original tensor shape is: {}".format(x.shape))

x = x.view(1,3,-1)
print("Reshaped tensor shape is: {}".format(x.shape))

Original tensor shape is: torch.Size([1, 3, 224, 224])
Reshaped tensor shape is: torch.Size([1, 3, 50176])


## Tranpose
$$a=
\begin{bmatrix}
1& 2\\
3& 4
\end{bmatrix}$$

$$a^T=
\begin{bmatrix}
1& 3\\
2& 4
\end{bmatrix}$$

In [4]:
x1 = torch.Tensor([[1,2],[3,4]])
print("Tensor a is: \n{}".format(x1))

x1_t = x1.t()
print("Tensor a^T is: \n{}".format(x1_t))

Tensor a is: 
tensor([[1., 2.],
        [3., 4.]])
Tensor a^T is: 
tensor([[1., 3.],
        [2., 4.]])


## Matrix multiplication
PyTorch에서 Matrix의 곱을 하는 방법

$$a=
\begin{bmatrix}
1& 2\\
3& 4
\end{bmatrix}$$

$$b=
\begin{bmatrix}
1& 1\\
1& 1
\end{bmatrix}$$

$$c=a\times b=
\begin{bmatrix}
1& 2\\
3& 4
\end{bmatrix}\times
\begin{bmatrix}
1& 1\\
1& 1
\end{bmatrix}=
\begin{bmatrix}
3& 3\\
7& 7
\end{bmatrix}$$

In [5]:
a = torch.Tensor([[1,2],[3,4]])
print("Tensor a is: \n{}".format(a))

b = torch.Tensor([[1,1],[1,1]])
print("Tensor b is: \n{}".format(b))

c = a*b
print("Tensor a*b is: \n{}".format(c))

c = torch.mm(a,b)
print("Tensor a × b is: \n{}".format(c))

c = a@b
print("Tensor a × b is: \n{}".format(c))

Tensor a is: 
tensor([[1., 2.],
        [3., 4.]])
Tensor b is: 
tensor([[1., 1.],
        [1., 1.]])
Tensor a*b is: 
tensor([[1., 2.],
        [3., 4.]])
Tensor a × b is: 
tensor([[3., 3.],
        [7., 7.]])
Tensor a × b is: 
tensor([[3., 3.],
        [7., 7.]])


## MSE loss
PyTorch에서 Mean Squared Error(MSE)를 계산하는 방법
$$
X=\{1,2,3\}
$$

$$
Y=\{3,3,3\}
$$

$$
\mathcal{L}(X,Y)= \frac{1}{3} \sum^3_{i=1}(x_i-y_i)^2\text{ where }x_i\in X, y_i\in Y$$

In [6]:
X = torch.Tensor([1,2,3])
Y = torch.Tensor([3,3,3])
L = nn.MSELoss()(X,Y)
print("MSE loss is: {:.4f}".format(L.item()))

MSE loss is: 1.6667


## L1 loss
PyTorch에서 L1 Error를 계산하는 방법
$$
X=\{1,2,3\}
$$

$$
Y=\{3,3,3\}
$$

$$
\mathcal{L}(X,Y)= \frac{1}{3} \sum^3_{i=1}|x_i-y_i|\text{ where }x_i\in X, y_i\in Y$$

In [7]:
X = torch.Tensor([1,2,3])
Y = torch.Tensor([3,3,3])
L = nn.L1Loss()(X,Y)
print("L1 loss is: {:.4f}".format(L.item()))

L1 loss is: 1.0000
